import { verifyChain } from '@comptra/core';
import type { LedgerRecord, Policy, AuditReport, Checkpoint } from '@comptra/schema';

/**
 * Assembles the self-contained, independently-checkable Agent Spend Audit Report —
 * the export that unblocks an enterprise security review. It carries the full canonical
 * records, the signed checkpoints, the public key + specs + an HONEST threat model, and a
 * pointer to the standalone verifier the auditor runs without trusting Comptra's servers.
 */
export async function buildReport(args: {
  tenantId: string;
  agentId: string | null;
  customerId: string | null;
  records: LedgerRecord[];
  checkpoints?: Checkpoint[];
  policy?: Policy;
  pubKeyHex: string;
  generatedAt: string;
}): Promise<AuditReport> {
  const v = await verifyChain(args.records);
  const sealed = args.records.filter((r) => r.decision === 'PASS').length;
  const blocked = args.records.length - sealed;
  return {
    report: 'comptra-agent-spend-audit',
    version: 1,
    generated_at: args.generatedAt,
    tenant_id: args.tenantId,
    scope: { agent_id: args.agentId, end_customer_id: args.customerId, from_ts: null, to_ts: null },
    summary: {
      records: args.records.length,
      sealed,
      blocked,
      verified: v.ok,
      root_hash: v.ok ? v.head : (args.records.at(-1)?.record_hash ?? null),
    },
    policy: args.policy,
    records: args.records,
    checkpoints: args.checkpoints ?? [],
    public_key: args.pubKeyHex,
    key_provenance:
      'Ed25519 signing key generated by this Comptra instance. In production the private key is held outside the ledger database trust domain (KMS/HSM); the public key here is what the auditor verifies against.',
    canonicalization_spec:
      'RFC 8785 JSON Canonicalization Scheme (JCS) over the full record field set excluding record_hash. Money is integer minor units (no floats). Timestamps are RFC3339 UTC.',
    hashing_spec:
      'record_hash = SHA-256( utf8(prev_hash_hex) || JCS(record_without_record_hash) ). Genesis prev_hash = 64 zero hex chars. prev_hash is inside the hash, so insert/delete/reorder/edit all fracture.',
    merkle_spec:
      'RFC 9162 domain-separated Merkle Tree Hash: leaf = SHA-256(0x00 || JCS(record)), node = SHA-256(0x01 || left || right). Checkpoints are Ed25519-signed over JCS(checkpoint without signature).',
    threat_model:
      'Tamper-evident against any post-hoc edit, insert, delete or reorder GIVEN the auditor retains signed checkpoints: verify() re-derives the chain + Merkle roots + signatures and localizes the first fractured seq. It does NOT yet defend against an operator split-view (showing different histories to different parties) — that requires external witnesses/cosigning, which is on the roadmap and the checkpoint format is designed to accept.',
    standalone_verifier:
      'Run `node bin/comptra.ts verify <ledger.jsonl> [--pubkey <hex>] [--checkpoints <file>]` to re-derive the chain, Merkle roots and signatures WITHOUT trusting Comptra servers. The verifier is pure and ships in @comptra/core.',
  };
}
