import {
  verifyChain, buildCheckpoint, leafHash, consistencyProof, proofToHex,
  witnessReview, freshWitnessState, type WitnessState,
} from '@comptra/core';
import type { LedgerRecord, Policy, AuditReport, Checkpoint, Cosignature, WitnessRef } from '@comptra/schema';

/** An in-process witness (in production each is an independent third-party service running the same code). */
export type ReportWitness = { witness_id: string; privateKey: CryptoKey; publicKeyHex: string; prevState?: WitnessState };

/**
 * Assembles the self-contained, independently-checkable Agent Spend Audit Report — the export that
 * unblocks an enterprise security review. It carries the canonical records, the Ed25519 signed
 * checkpoint, a t-of-n WITNESS QUORUM (the split-view defense), the public keys + specs + an honest
 * threat model, and a pointer to the standalone verifier the auditor runs without trusting Comptra.
 */
export async function buildReport(args: {
  tenantId: string;
  agentId: string | null;
  customerId: string | null;
  records: LedgerRecord[];
  checkpoints?: Checkpoint[];
  policy?: Policy;
  pubKeyHex: string;
  generatedAt: string;
  signer?: { privateKey: CryptoKey; keyId: string };
  witnessing?: { threshold: number; witnesses: ReportWitness[] };
}): Promise<AuditReport> {
  const v = await verifyChain(args.records);
  const sealed = args.records.filter((r) => r.decision === 'PASS').length;
  const blocked = args.records.length - sealed;

  let checkpoints: Checkpoint[] = args.checkpoints ?? [];
  let witnessing: AuditReport['witnessing'];

  if (args.signer && args.records.length > 0) {
    const chainKey = args.agentId ? `${args.tenantId}|${args.agentId}|${args.customerId ?? '-'}` : `${args.tenantId}|*|*`;
    const cp = await buildCheckpoint({
      tenant_id: args.tenantId, chain_key: chainKey, records: args.records,
      key_id: args.signer.keyId, ts: args.generatedAt, signPrivateKey: args.signer.privateKey,
    });

    // gather an independent witness quorum over this head (the split-view defense)
    if (args.witnessing && args.witnessing.witnesses.length) {
      const leaves = await Promise.all(args.records.map(leafHash));
      const cosignatures: Cosignature[] = [];
      const registry: WitnessRef[] = [];
      for (const w of args.witnessing.witnesses) {
        const state = w.prevState ?? freshWitnessState();
        const proof = proofToHex(await consistencyProof(leaves, state.tree_size, args.records.length));
        const rev = await witnessReview({
          state, checkpoint: cp, operatorPubKeyHex: args.pubKeyHex, consistencyProofHex: proof,
          witnessId: w.witness_id, witnessPrivateKey: w.privateKey, ts: args.generatedAt,
        });
        registry.push({ witness_id: w.witness_id, public_key: w.publicKeyHex, operator: 'independent' });
        if (rev.ok) cosignatures.push(rev.cosignature);
      }
      cp.cosignatures = cosignatures;
      witnessing = {
        threshold: args.witnessing.threshold,
        witnesses: registry,
        note: `Independent t-of-n witness quorum (${args.witnessing.threshold}-of-${registry.length}). Each witness cosigns only after verifying an RFC 9162 consistency proof from the last head it saw, so a split-view fork cannot reach quorum. Verify offline with: comptra verify <report.json>.`,
      };
    }
    checkpoints = [...checkpoints, cp];
  }

  const rootHash = checkpoints.at(-1)?.root_hash ?? (v.ok ? v.head : (args.records.at(-1)?.record_hash ?? null));
  return {
    report: 'comptra-agent-spend-audit',
    version: 1,
    generated_at: args.generatedAt,
    tenant_id: args.tenantId,
    scope: { agent_id: args.agentId, end_customer_id: args.customerId, from_ts: null, to_ts: null },
    summary: { records: args.records.length, sealed, blocked, verified: v.ok, root_hash: rootHash },
    policy: args.policy,
    records: args.records,
    checkpoints,
    witnessing,
    public_key: args.pubKeyHex,
    key_provenance:
      'Ed25519 signing key generated by this Comptra instance. In production the private key is held outside the ledger database trust domain (KMS/HSM); the public key here is what the auditor verifies against. Witness keys belong to independent third parties.',
    canonicalization_spec:
      'RFC 8785 JSON Canonicalization Scheme (JCS) over the full record field set excluding record_hash. Money is integer minor units (no floats). Timestamps are RFC3339 UTC.',
    hashing_spec:
      'record_hash = SHA-256( utf8(prev_hash_hex) || JCS(record_without_record_hash) ). Genesis prev_hash = 64 zero hex chars. prev_hash is inside the hash, so insert/delete/reorder/edit all fracture.',
    merkle_spec:
      'RFC 9162 domain-separated Merkle Tree Hash: leaf = SHA-256(0x00 || JCS(record)), node = SHA-256(0x01 || left || right). Inclusion proofs are O(log n); consistency proofs prove append-only between checkpoints. Checkpoints are Ed25519-signed over JCS(checkpoint without signature or cosignatures).',
    threat_model:
      'Tamper-evident AND split-view-resistant. (1) Any post-hoc edit/insert/delete/reorder fractures the SHA-256 hash chain at an exact seq. (2) An operator with full DB write access cannot rewrite history committed in a retained Ed25519 checkpoint. (3) A malicious operator cannot present two divergent histories: each independent witness cosigns a new head ONLY after verifying an RFC 9162 consistency proof from the last head it saw, so a fork cannot reach the t-of-n quorum. The remaining assumption is minimal and named: at least one witness is honest and reachable, and the auditor retains one checkpoint + the witness public keys.',
    standalone_verifier:
      'Run `comptra verify <report.json>` to re-derive the chain + Merkle roots, verify the Ed25519 checkpoint signature, AND verify the witness quorum — all WITHOUT trusting Comptra servers. The verifier is pure and ships in @comptra/core; anyone can also run `comptra witness` to BE a witness.',
  };
}
